<footer class="footer">
  <div class="container flex justify-between items-center column-mobile">
    <div class="footer-brand">
      <p>&copy; 2024 Ninja. All Rights Reserved.</p>
    </div>
    <div class="footer-links">
      <ul class="flex gap-4">
        <li><a href="/support">Support</a></li>
        <li><a href="/terms">Terms</a></li>
        <li><a href="/privacy">Privacy</a></li>
      </ul>
    </div>
    <div class="footer-signature">
      <p style="color: #10A500;">Built by <a href="https://www.bougroup.org/technology.html" target="_blank"
          rel="noopener noreferrer">BOU</a>
      </p>
    </div>
  </div>
</footer>

<!-- Bottom Navigation for Mobile -->
<div class="bottom-nav-container">
  <nav class="bottom-nav">
    <ul class="flex justify-between w-full">
      <li><a href="/"><i class="ph-duotone ph-house-line"></i><span>Home</span></a></li>
      <li><a href="/wallet/"><i class="ph-duotone ph-wallet"></i><span>Wallet</span></a></li>
      <li><a href="/api/keys/"><i class="ph-duotone ph-key"></i><span>Keys</span></a></li>
      <li><a href="/logs/"><i class="ph-duotone ph-terminal-window"></i><span>Logs</span></a></li>
      <li><a href="/kyb/"><i class="ph-duotone ph-shield-check"></i><span>KYB</span></a></li>
    </ul>
  </nav>
</div>